import type { ToolMetadata } from '@walikelas/types';

export const TOOLS: ToolMetadata[] = [
  // P0 Local Tools (Phase 4: Available)
  {
    id: 'timer',
    name: 'Timer',
    description: 'Stopwatch, hitung mundur, dan pengingat waktu pembelajaran.',
    category: 'LOCAL',
    isInteractive: false,
    requiresAuth: false,
    priority: 'P0',
    route: '/tools/timer',
    iconName: 'timer',
    status: 'AVAILABLE',
  },
  {
    id: 'random-picker',
    name: 'Random Picker',
    description: 'Pemilih acak nama siswa, giliran, atau kelompok.',
    category: 'LOCAL',
    isInteractive: false,
    requiresAuth: false,
    priority: 'P0',
    route: '/tools/random-picker',
    iconName: 'random-picker',
    status: 'AVAILABLE',
  },
  {
    id: 'group-maker',
    name: 'Group Maker',
    description: 'Pembagi kelompok otomatis berdasarkan jumlah anggota atau jumlah tim.',
    category: 'LOCAL',
    isInteractive: false,
    requiresAuth: false,
    priority: 'P0',
    route: '/tools/group-maker',
    iconName: 'group-maker',
    status: 'AVAILABLE',
  },
  {
    id: 'scoreboard',
    name: 'Scoreboard',
    description: 'Papan skor sederhana untuk kompetisi tim di kelas.',
    category: 'LOCAL',
    isInteractive: false,
    requiresAuth: false,
    priority: 'P1',
    route: '/tools/scoreboard',
    iconName: 'scoreboard',
    status: 'AVAILABLE',
  },
  {
    id: 'teacher-notes',
    name: 'Teacher Notes',
    description: 'Catatan cepat guru selama sesi pembelajaran berlangsung.',
    category: 'LOCAL',
    isInteractive: false,
    requiresAuth: true,
    priority: 'P0',
    route: '/tools/notes',
    iconName: 'teacher-notes',
    status: 'AVAILABLE',
  },

  // Interactive Tools (Upcoming)
  {
    id: 'live-quiz',
    name: 'Live Quiz',
    description: 'Kuis interaktif langsung dengan leaderboard dan feedback instan.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P0',
    route: '/tools/live-quiz',
    iconName: 'live-quiz',
    status: 'AVAILABLE',
  },
  {
    id: 'live-poll',
    name: 'Live Poll',
    description: 'Jajak pendapat kilat untuk mengukur pemahaman atau opini siswa.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P0',
    route: '/tools/live-poll',
    iconName: 'live-poll',
    status: 'AVAILABLE',
  },
  {
    id: 'raise-hand',
    name: 'Raise Hand',
    description: 'Antrean angkat tangan digital untuk partisipasi teratur.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P1',
    route: '/tools/raise-hand',
    iconName: 'raise-hand',
    status: 'AVAILABLE',
  },
  {
    id: 'question-box',
    name: 'Question Box',
    description: 'Kotak pertanyaan anonim atau bernama dari siswa.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P1',
    route: '/tools/question-box',
    iconName: 'question-box',
    status: 'AVAILABLE',
  },
  {
    id: 'brainstorm-board',
    name: 'Brainstorm Board',
    description: 'Papan ide kolaboratif untuk mengumpulkan gagasan kelas.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P1',
    route: '/tools/brainstorm-board',
    iconName: 'brainstorm-board',
    status: 'AVAILABLE',
  },
  {
    id: 'word-cloud',
    name: 'Word Cloud',
    description: 'Visualisasi kata dinamis dari respon singkat seluruh kelas.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P1',
    route: '/tools/word-cloud',
    iconName: 'word-cloud',
    status: 'COMING_SOON',
  },
  {
    id: 'exit-ticket',
    name: 'Exit Ticket',
    description: 'Refleksi singkat di akhir pelajaran sebelum siswa meninggalkan kelas.',
    category: 'INTERACTIVE',
    isInteractive: true,
    requiresAuth: true,
    priority: 'P1',
    route: '/tools/exit-ticket',
    iconName: 'exit-ticket',
    status: 'AVAILABLE',
  },

  // Content Tool (Upcoming)
  {
    id: 'flashcards',
    name: 'Flashcards',
    description: 'Kartu pengingat materi untuk pengulangan dan penguatan konsep.',
    category: 'CONTENT',
    isInteractive: false,
    requiresAuth: false,
    priority: 'P2',
    route: '/tools/flashcards',
    iconName: 'flashcards',
    status: 'COMING_SOON',
  },
];
